version: '3.8'

services:
  spring-boot-app:
    image: openjdk:17
    container_name: banking-app
    working_dir: /app
    volumes:
      - ./target/banking-app-0.0.1-SNAPSHOT.jar:/app/banking-app-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/banking_app
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456Aa*
    depends_on:
      - db
    command: ["java", "-jar", "banking-app-0.0.1-SNAPSHOT.jar"]

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456Aa*
      MYSQL_DATABASE: banking_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
